CREATE TABLE IF NOT EXISTS add_party(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Party_Id VARCHAR(255) NOT NULL UNIQUE,
    Party_Name VARCHAR(20) NOT NULL,
    GSTIN VARCHAR(255) DEFAULT NULL,
    Phone_Number VARCHAR(20) DEFAULT NULL,
   
    State VARCHAR(255) DEFAULT NULL,
    Email_Id VARCHAR(255) DEFAULT NULL,
    Billing_Address VARCHAR(255) DEFAULT NULL,
    Shipping_Address VARCHAR(255) DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
   
)
-- ALTER TABLE add_party 
-- ADD CONSTRAINT uq_party UNIQUE (Party_Id);