
CREATE TABLE IF NOT EXISTS add_food_item(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Item_Id VARCHAR(255) NOT NULL,
    Item_Name VARCHAR(255) NOT NULL,
    Item_Description VARCHAR(255) NOT NULL,
    Item_Category VARCHAR(255) NOT NULL,
    Item_Price DECIMAL(10,2) NOT NULL,
    Item_Quantity INT(10) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)