CREATE TABLE IF NOT EXISTS add_table(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Table_Id VARCHAR(255) NOT NULL UNIQUE,
    Table_Name VARCHAR(255) NOT NULL,
    Start_Time DATETIME NOT NULL,
    End_Time DATETIME NOT NULL,
    Table_Capacity INT NOT NULL,
    Status ENUM('available','occupied','reserved') DEFAULT 'available'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)