CREATE TABLE IF NOT EXISTS add_category(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Category_Id VARCHAR(255) NOT NULL UNIQUE,
    Item_Category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
-- index name is Category_Id