CREATE TABLE IF NOT EXISTS add_material(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  material_id VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  unit VARCHAR(20) NOT NULL,   
  current_stock VARCHAR(255) NOT NULL,   
  reorder_level VARCHAR(255) NOT NULL,   
  shelf_life_days INT,           
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

)