CREATE TABLE customers ( 
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
Customer_Id VARCHAR(255) NOT NULL UNIQUE, 
Customer_Name VARCHAR(255) NOT NULL, 
Customer_Phone VARCHAR(15) NOT NULL, 
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 )