CREATE TABLE kitchen_order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    KOT_Item_Id VARCHAR(255) NOT NULL UNIQUE,
    KOT_Id VARCHAR(255) NOT NULL,
    Item_Id VARCHAR(255) NOT NULL,
    Item_Name VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL,
    created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

 
);
