CREATE TABLE order_items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    Order_Item_Id VARCHAR(255) NOT NULL UNIQUE,
    Order_Id VARCHAR(255) NOT NULL,
    Item_Id VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL DEFAULT 1,
    Price DECIMAL(10,2) NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
   
);
