CREATE TABLE order_tables (
    id INT PRIMARY KEY AUTO_INCREMENT,
    Order_Table_Id VARCHAR(255) NOT NULL UNIQUE,
    Order_Id VARCHAR(255) NOT NULL,
    Table_Id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
   
);
