CREATE TABLE invoice_public_links (
    
 id INT AUTO_INCREMENT PRIMARY KEY,
 Invoice_Public_Link_Id VARCHAR(255) NOT NULL UNIQUE,
  Invoice_Id VARCHAR(255) NOT NULL,
  Order_Id VARCHAR(255) NOT NULL,
  Customer_Id VARCHAR(255) NOT NULL,
  Public_Token VARCHAR(255) NOT NULL UNIQUE,
 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
 