CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  User_Id VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(100),
  phone VARCHAR(20) UNIQUE,
  email VARCHAR(100) UNIQUE,
  username VARCHAR(255),
  password VARCHAR(255),
 
  address VARCHAR(255),
  pincode VARCHAR(20),
  city VARCHAR(255),
  admin_id INT NOT NULL,
  role enum('admin', 'user') DEFAULT 'user', VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

